### ISSUE TITLE
Shipping example workspace declaration differs from portal

### ISSUE THREAD

**Issue by tonybaloney** [microsoft/qio-samples#19]
In the portal, after creating the workspace it gives the QuickStart steps:

```
Download and run your first optimization job

Download from GitHub the shipping-sample.py

Update sample with your workspace information

workspace = Workspace (
  subscription_id = "bde9dbe7-xxxx-xxxx-xxxx-xxxxxxxxxx",
  resource_group = "quantum_testing",
  name = "ant-quantum-testing",
  location = "westus2"
)
Run sample
```

But in `shipping-sample.py`, the workspace definition is 

```python
# Copy the settings for your workspace below
workspace = Workspace(
    resource_id = "", # add the Resource ID of your Azure Quantum workspace
    location = ""     # add the location of your Azure Quantum workspace (e.g. "westus")
)
```

These seem to be two different supported configuration options.

It took me a while to work out which option was the correct one.

**Comment by frtibble** [comment]
Thank you @tonybaloney for flagging this, and sorry for the time you had to spend working out which was the correct one to use - I've updated all of the samples so that they're consistent with what the portal recommends, and will be tracking future updates so we don't run into this again. Thank you!
